{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-core",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0-SNAPSHOT.jar",
          "url": "salty-core-0.0.0-SNAPSHOT.jar",
          "size": 11048,
          "sha512": "0e4ac5c04c144dfc537c04637021bd2805aec3fbcb8f132c1e722b46dd14008ed2e5bad985f00ade861ba3d53f494d07edd3ded9f9480ef02718fa9751fb726d",
          "sha256": "6d557293dd599a22a3efd6894e071cd191921a284731d5933726bc06900b26b6",
          "sha1": "13779adbfbe9b8662670e3c64b473f255ed77254",
          "md5": "e8d4085f0ba282c7f59078e6a815e998"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.gratatouille",
          "module": "gratatouille-core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0-SNAPSHOT.jar",
          "url": "salty-core-0.0.0-SNAPSHOT.jar",
          "size": 11048,
          "sha512": "0e4ac5c04c144dfc537c04637021bd2805aec3fbcb8f132c1e722b46dd14008ed2e5bad985f00ade861ba3d53f494d07edd3ded9f9480ef02718fa9751fb726d",
          "sha256": "6d557293dd599a22a3efd6894e071cd191921a284731d5933726bc06900b26b6",
          "sha1": "13779adbfbe9b8662670e3c64b473f255ed77254",
          "md5": "e8d4085f0ba282c7f59078e6a815e998"
        }
      ]
    }
  ]
}
