{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-core",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0-SNAPSHOT.jar",
          "url": "salty-core-0.0.0-SNAPSHOT.jar",
          "size": 11048,
          "sha512": "389c2e18917e7703d5213ce2d9738b3eee74071ac858a48dd4af62e26ff511fbc9aabf2b5a79006c469e32e7fe2112bf7dc57bc083bb37be7633f07f3483eb48",
          "sha256": "f084f376ea64be37d3c264996bc9072a3551a817680731a583f76a22788670d6",
          "sha1": "c9ce39ad21ca9d0689dfd8e62ad25716a49c9db2",
          "md5": "00bdce17e3ab2c51bfb1cda930a1044d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.gratatouille",
          "module": "gratatouille-core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0-SNAPSHOT.jar",
          "url": "salty-core-0.0.0-SNAPSHOT.jar",
          "size": 11048,
          "sha512": "389c2e18917e7703d5213ce2d9738b3eee74071ac858a48dd4af62e26ff511fbc9aabf2b5a79006c469e32e7fe2112bf7dc57bc083bb37be7633f07f3483eb48",
          "sha256": "f084f376ea64be37d3c264996bc9072a3551a817680731a583f76a22788670d6",
          "sha1": "c9ce39ad21ca9d0689dfd8e62ad25716a49c9db2",
          "md5": "00bdce17e3ab2c51bfb1cda930a1044d"
        }
      ]
    }
  ]
}
