{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-gradle-plugin",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-gradle-plugin-0.0.0.jar",
          "url": "salty-gradle-plugin-0.0.0.jar",
          "size": 23662,
          "sha512": "28e4a005a2d4864149037e941a67b8582d25315c283a6152a6a8924ca19587f99e927f701a325f0cec4c57af1743ec7a70b49fa7537fab2de9fe71dcf294c13f",
          "sha256": "80561386da96a67c822c9a473d7cf06472926dc740eb2711d57747550e2c78d6",
          "sha1": "7bc521787a116fbd26690fe2d316f696b34857d0",
          "md5": "4f074c13e25cc0dc9560f03329e6ed4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-gradle-plugin-0.0.0.jar",
          "url": "salty-gradle-plugin-0.0.0.jar",
          "size": 23662,
          "sha512": "28e4a005a2d4864149037e941a67b8582d25315c283a6152a6a8924ca19587f99e927f701a325f0cec4c57af1743ec7a70b49fa7537fab2de9fe71dcf294c13f",
          "sha256": "80561386da96a67c822c9a473d7cf06472926dc740eb2711d57747550e2c78d6",
          "sha1": "7bc521787a116fbd26690fe2d316f696b34857d0",
          "md5": "4f074c13e25cc0dc9560f03329e6ed4e"
        }
      ]
    }
  ]
}
