{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-gradle-plugin",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-gradle-plugin-0.0.0.jar",
          "url": "salty-gradle-plugin-0.0.0.jar",
          "size": 23662,
          "sha512": "e884d14eea9e47f1996a71b07a75988622f3ee553f50e6f8b5a2c41e775957e8054aa24ac055b10da1d8e4bacf430f6cf699c916899d1344da32771f4af93d81",
          "sha256": "043c2caa45c178482905c38c899873174bc3d4551aecda93228d0ad392846773",
          "sha1": "ae5b8e335fdec5fefb299ccec740cba7f5389364",
          "md5": "ff0cab516522b0b63fa6035535943007"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-gradle-plugin-0.0.0.jar",
          "url": "salty-gradle-plugin-0.0.0.jar",
          "size": 23662,
          "sha512": "e884d14eea9e47f1996a71b07a75988622f3ee553f50e6f8b5a2c41e775957e8054aa24ac055b10da1d8e4bacf430f6cf699c916899d1344da32771f4af93d81",
          "sha256": "043c2caa45c178482905c38c899873174bc3d4551aecda93228d0ad392846773",
          "sha1": "ae5b8e335fdec5fefb299ccec740cba7f5389364",
          "md5": "ff0cab516522b0b63fa6035535943007"
        }
      ]
    }
  ]
}
