{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-core",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0.jar",
          "url": "salty-core-0.0.0.jar",
          "size": 11005,
          "sha512": "d4600f188d77a9282b029bc3c4e6a41383e781d658a3cb92bcacecaa6f1ebea47bb1cada19931a006408e59bc45b53302a971d86f372523e79c0a74d5787a6ec",
          "sha256": "3e37dc940aabc163ec9eb7235ae0aeabd4bc2ba1564d2785024ae9662aeb165d",
          "sha1": "a4c1896994f8fcbf91d4de320b2af2dc2ef936fd",
          "md5": "f711d88411a4886ba52bf3147e1011e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.gratatouille",
          "module": "gratatouille-core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0.jar",
          "url": "salty-core-0.0.0.jar",
          "size": 11005,
          "sha512": "d4600f188d77a9282b029bc3c4e6a41383e781d658a3cb92bcacecaa6f1ebea47bb1cada19931a006408e59bc45b53302a971d86f372523e79c0a74d5787a6ec",
          "sha256": "3e37dc940aabc163ec9eb7235ae0aeabd4bc2ba1564d2785024ae9662aeb165d",
          "sha1": "a4c1896994f8fcbf91d4de320b2af2dc2ef936fd",
          "md5": "f711d88411a4886ba52bf3147e1011e3"
        }
      ]
    }
  ]
}
