{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-core",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0.jar",
          "url": "salty-core-0.0.0.jar",
          "size": 11005,
          "sha512": "a8ae886e522dc3e38f30b15367b5eee15094b0562731826d352b4a6cf2dabc95ce5e5adf696c1cbccb9a02b0884d5869e9ee58ae5b975a6511fdb3ced68e8c78",
          "sha256": "77e908f9b2824a472e3572be0ccbd9e7dfced6a6c84496f8025309751cd81f5b",
          "sha1": "0d47a22363f3e389b4d5d746cc1c0a60ff7a97c7",
          "md5": "bc7df8795fa2323159a928159323feea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.gratatouille",
          "module": "gratatouille-core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0.jar",
          "url": "salty-core-0.0.0.jar",
          "size": 11005,
          "sha512": "a8ae886e522dc3e38f30b15367b5eee15094b0562731826d352b4a6cf2dabc95ce5e5adf696c1cbccb9a02b0884d5869e9ee58ae5b975a6511fdb3ced68e8c78",
          "sha256": "77e908f9b2824a472e3572be0ccbd9e7dfced6a6c84496f8025309751cd81f5b",
          "sha1": "0d47a22363f3e389b4d5d746cc1c0a60ff7a97c7",
          "md5": "bc7df8795fa2323159a928159323feea"
        }
      ]
    }
  ]
}
