{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-core",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0.jar",
          "url": "salty-core-0.0.0.jar",
          "size": 11005,
          "sha512": "69771eb0ab90769f29fa01503ff7ed0161e7efdaa29e146defaff19cd1291df701c71d21b39ca57ae769cc97052aa5114db54f8550ef3d8eb2a4ac6b11a639ec",
          "sha256": "5f0cc74f16eb7a933eeedc5e4be226e1774f84455dc449a837fc0b82d789bc90",
          "sha1": "c59d3d2f35c1aafbc74e79d482f77fd8587e1788",
          "md5": "81e9e274015b48826b552790683367d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradleup.gratatouille",
          "module": "gratatouille-core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-core-0.0.0.jar",
          "url": "salty-core-0.0.0.jar",
          "size": 11005,
          "sha512": "69771eb0ab90769f29fa01503ff7ed0161e7efdaa29e146defaff19cd1291df701c71d21b39ca57ae769cc97052aa5114db54f8550ef3d8eb2a4ac6b11a639ec",
          "sha256": "5f0cc74f16eb7a933eeedc5e4be226e1774f84455dc449a837fc0b82d789bc90",
          "sha1": "c59d3d2f35c1aafbc74e79d482f77fd8587e1788",
          "md5": "81e9e274015b48826b552790683367d6"
        }
      ]
    }
  ]
}
