{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gradleup.salty",
    "module": "salty-gradle-plugin",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-gradle-plugin-0.0.0-SNAPSHOT.jar",
          "url": "salty-gradle-plugin-0.0.0-SNAPSHOT.jar",
          "size": 23671,
          "sha512": "6d14a29003089121fb5cff945344a1551ef8496139aa153c645c4bbbc54e9b65222f1f54ad64f761121b583af4a217b9510f752e3e4ef881cc73aba0e4d12b19",
          "sha256": "03ddf3053f6b3be6c5acf2d9e4a73d1a61d7a1d70cf1d6a3d2bcd872568c96f8",
          "sha1": "4322b5797d857cc416feda940cd48bdd1b11fa5f",
          "md5": "71c87b9557f0feee6e5ca22b31ab2b59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "salty-gradle-plugin-0.0.0-SNAPSHOT.jar",
          "url": "salty-gradle-plugin-0.0.0-SNAPSHOT.jar",
          "size": 23671,
          "sha512": "6d14a29003089121fb5cff945344a1551ef8496139aa153c645c4bbbc54e9b65222f1f54ad64f761121b583af4a217b9510f752e3e4ef881cc73aba0e4d12b19",
          "sha256": "03ddf3053f6b3be6c5acf2d9e4a73d1a61d7a1d70cf1d6a3d2bcd872568c96f8",
          "sha1": "4322b5797d857cc416feda940cd48bdd1b11fa5f",
          "md5": "71c87b9557f0feee6e5ca22b31ab2b59"
        }
      ]
    }
  ]
}
